#端口配置
server:
  port: 8848
spring:
  mail:
    #    邮箱账号
    username: ftf_opensource@qq.com
    #    邮箱客户端授权码
    password: zpqvqbayyzhfebaa
    #    邮箱服务器地址
    host: smtp.qq.com
    properties:
      mail:
        smtp:
          ssl:
            enable: true